### ISSUE TITLE
Check box to mark as station as already worked.

### ISSUE THREAD

**Issue by adammelancon** [mbridak/potato#2]
Think it would be cool to have a checkbox that you can click on to turn the line red to mark that you have already worked that station.  Nothing has to be saved, it would just be a quick neat visual indicator that you don't have to hunt that one anymore.

**Comment by mbridak** [comment]
I pretty much did this. Instead of a checkbox you just doubleclick the activator to mark them.

**Comment by adammelancon** [comment]
That’s awesome! Thanks!!!
