### ISSUE TITLE
Frequency decimal places

### ISSUE THREAD

**Issue by mattbk** [mbridak/potato#9]
**Describe the bug**
potato doesn't seem to have as many decimal places for frequency as sotacracker does. Sometimes I will need to tune up slightly to find the right frquency.

**To Reproduce**
See image below. Find a spot like 10.1119 MHz. potato will only show 10.111, and only change the rig to 10.111.

<img width="1365" alt="image" src="https://github.com/mbridak/potato/assets/3729038/a1955d8c-f42e-404a-b6f0-19de19d51d43">

**Expected behavior**
Expect that all the frquency decimal places in the spot will be shown in potato and used for rig control.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser N/A
 - Version 22.2.19

**Additional context**
I realize that augratin is probably a better program and where development is going, but I can't get it to work on Windows.

**Comment by mbridak** [comment]
Okay. Made the changes. let me know if I broke something in the process.

![image](https://github.com/mbridak/potato/assets/49108421/ec701742-c1ad-4943-9d88-ad079cafe7e3)

**Comment by mattbk** [comment]
Seems to work great. Thanks!
